### ISSUE TITLE
Not an issue - question around apfs structure / recover container states 

### ISSUE THREAD

**Issue by johndpope** [linux-apfs/linux-apfs#1]
In paper decoding apfs file system
Page 4  / they mention it’s possible to programmatically recover container states.

Has there been any work around this? My ssd cacked it and I’m trying to get drive back up with folder / directory structures.
![image](https://user-images.githubusercontent.com/289994/43362268-4530d1f0-92b4-11e8-83b7-35fce2b91f94.jpg)

**Comment by eafer** [comment]
Hi:

I use github only for hosting. You'll get faster replies if you send me an email.

What that paragraph is talking about is recovering modified or deleted data from a valid APFS volume, which can usually be done because of the copy-on-write. That won't necessarily be of help if your drive is damaged, since the old checkpoints should be as affected as the current one.

Also, if your SSD is dead I think the real challenge will be to recover reasonable raw data from it. Have you managed that already?

**Comment by johndpope** [comment]
I was using ssd drive via usb which was disconnected and then reconnected. 

**+-- Container ERROR -69808
    ======================
    APFS Container Reference:     disk4
    Size (Capacity Ceiling):      ERROR -69620
    Capacity In Use By Volumes:   ERROR -69524
    Capacity Not Allocated:       ERROR -69524
    |
    +-< Physical Store disk3s2 B8843099-2B4F-4D1B-909A-DB5B1B516B9C
    |   -----------------------------------------------------------
    |   APFS Physical Store Disk:   disk3s2
    |   Size:                       999666946048 B (999.7 GB)

https://gist.github.com/johndpope/1070ac3f027bdbffc7818c09533ac474

I ran disk drill and have a backup image of drive. 

diskutil verifyVolume disk3
Started file system verification on disk3
Verifying storage system
Performing fsck_apfs -n -x /dev/disk2s2
Checking volume
Checking the container superblock
Checking the EFI jumpstart record
Checking the space manager
error: (oid 0x8790) cib: invalid o_xid (0x63f69)
error: **failed to read spaceman cib** 0x8790
**Space manager is invalid**

I thought crudely - I may be able to import the data into another apfs container??
My latest thinking is that a chunk of the data is gone, as I have ran disk drill across drive - but it was missing specific files perhaps indicating that the drive tried to bail out.

**Comment by eafer** [comment]
So you are saying the SSD is not damaged, it was only unplugged while running? That should not cause corruption on a copy-on-write filesystem. It sounds like a bug.

I'm not familiar with macOS software or error messages. I'm guessing the space manager must be the allocation bitmap, which should not matter for a read-only mount. Have you tried mounting read-only? What happens then?

Have you tried mounting with my module under linux? We don't even read the allocation bitmap, so it may work. Even if it doesn't I will at least recognize the error messages and be able to help you. If you actually need to read an old checkpoint, I think I can send you a patch for that.

That said, keep in mind we don't yet support compression or encryption. Even if it mounts some of your files may not be readable.

**Comment by johndpope** [comment]
It did recover fine upon disconnect and reconnect which surprised me. Majove OS carried on like there was no problem. The edge case here when things when pear shaped (pointing to the bug) this one time when drive disconnected - I plugged the drive into the other port on other side of macbook. Then back again to original port then.... Kaboom. 

Thanks for suggestion.  I'm going to build an ubunto iso usb and fire up to a linux kernal. 

(compression or encryption not a problem) 
side note - I noticed in latest mojave v5 this repair allocation flag in fsck_apfs -
yet to try it. 
![screen shot 2018-08-01 at 11 00 50 am](https://user-images.githubusercontent.com/289994/43529857-31c4731a-957a-11e8-8bed-214d374a450c.png)

**Comment by johndpope** [comment]
I'm having some luck with iBoySoft apfs partition recovery. Thanks for your help. 
![screen shot 2018-08-01 at 11 25 16 am](https://user-images.githubusercontent.com/289994/43532375-e8ea087a-957f-11e8-8f49-9a7e4c45eec5.png)

**Comment by iggysniggy** [comment]
Did you have any luck, @johndpope?

I'm not tech-savvy, so here goes:

I have the same issue where First Aid run through Disk Utility reads:

---
Running First Aid on “” (disk0s2)

Repairing storage system
Performing fsck_apfs -y -x /dev/disk0s2
Checking the container superblock.
Checking the EFI jumpstart record.
Checking the space manager.
error: (oid 0x27216) cib: found zeroed-out block
error: failed to read spaceman cib 0x27216
Space manager is invalid.
The volume /dev/disk0s2 could not be verified completely.
Storage system check exit code is 0.

Operation successful.
---

I was and am on MacOS Catalina.
I've tried a ton of recovery software, but none of them recover all photos, videos and audio perfectly, though iBeesoft does a pretty good job and has a good price.

Have you tried to see if there is a fix for the issue that restores the container to full functionality?

**Comment by johndpope** [comment]
the software iBoySoft (tried several of them unsuccessfully) resolved things enough to recover data.
